### ISSUE TITLE
Remove windows from plugin name (excluding artifact ID)

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-storage-plugin#181]
I think we should remove 'windows' from the plugin name.

This covers:

* anywhere it's displayed in the UI
* pom.xml (except artifact ID)
* GitHub repo name
* Any documentation

We can't update the artifact ID as otherwise people can't update to newer versions

@xuzhang3 any objections?

**Comment by xuzhang3** [comment]
I have no questions. This plugin focus on azure storage, windows have nothing to do with this plugin.
