### ISSUE TITLE
Upload to Azure Blob Storage -> Container name question

### ISSUE THREAD

**Issue by italoveloso89** [jenkinsci/azure-storage-plugin#208]
### Version report

Jenkins and plugins versions report:

Plugins:
Azure AD Plugin - 185.v3b416408dcb1
Azure Artifact Manager plugin - 97.v074e1332e88d
Azure CLI Plugin - 0.9
Azure Credentials - 198.vf9c2fdfde55c
Azure SDK API Plugin - 70.v63f6a95999a7
Azure Storage plugin - 365.vf41653c43b01
Azure VM Agents - 799.va4c741108611

Jenkins version: 2.303.3

- What Operating System are you using (both controller, and any agents involved in the problem)?
Windows 2019 server only master

### Reproduction steps

Hi guys, actually, I have a question. 

In Snippet Generator -> Sample step (AzureUpload: Upload Artifacts to Azure Storage) - > Azure Storage type -> Upload to Azure Blob Storage(Container Name).
My container name is: testproject
How do I do create inside this container, a folder with the name BUILD_NUMBER?

Because this field doesn't accept slash, only letters, numbers and dashes

today this is my syntax: 
`azureUpload blobProperties: [contentLanguage: 'en-US'], containerName: 'testproject', filesPath: 'DeEscalationXR/Deploy/*', storageCredentialId: 'TestUploadArtifactsAzure', storageType: 'blobstorage'`

**Comment by timja** [comment]
try setting `virtualPath` https://www.jenkins.io/doc/pipeline/steps/windows-azure-storage/#azureupload-upload-artifacts-to-azure-storage

the docs aren't too clear though what it does.

**Comment by italoveloso89** [comment]
Apparently, it worked. 
Do you know if this plugin has any file size limitations to upload? Because I'm trying to upload files with 1GB more and it didn't work. Only small files did work.

**Comment by timja** [comment]
It should work, there's been issues in the past that I've fixed, there was a recent issue opened here: https://github.com/jenkinsci/azure-artifact-manager-plugin/issues/32

**Comment by italoveloso89** [comment]
To upload to Azure Blob, should I archive(archiveArtifacts) first and then use Azure storage plugin(azureUpload blobProperties)?
The files that I need to upload are big files(1GB).
Because Azure storage plugin didn't work, stay in upload stage forever. it didn't upload the big files, only uploaded to azure .txt files.

**Comment by timja** [comment]
if you are archiving large files you should probably be using this plugin:
https://github.com/jenkinsci/azure-artifact-manager-plugin/

Which generally works although there is this issue: https://github.com/jenkinsci/azure-artifact-manager-plugin/issues/32
