### ISSUE TITLE
/**/*.* includeFilesPattern ant syntax only selects first dir occurrence 

### ISSUE THREAD

**Issue by lucajung** [jenkinsci/azure-storage-plugin#232]
### Jenkins and plugins versions report

OS: Linux

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Directory structure
```
import   
│
└───aaa
│   │   file1.xml
│   │   file2.xml
└───bbb
│   │   file3.xml
│   │   file4.xml
```
2. execute
``` 
azureDownload downloadType: 'share', fileShare: '...', includeFilesPattern: 'import/**/*.*', storageCredentialId: '...'
```

### Expected Results

file1.xml, file2.xml, file3.xml, file4.xml are downloaded.

### Actual Results

Only file1.xml and file2.xml are downloaded.

**Comment by lucajung** [comment]
Are there any news?

**Comment by timja** [comment]
Contributions welcome, I don't have much time here currently but I can review, test and merge pull requests.

**Comment by lucajung** [comment]
Ok, I can provide a PR. How can I debug the plugin in VS Code? @timja

**Comment by timja** [comment]
I don't use VS Code for Java development so you'll have to google it. (I use intellij)

**Comment by lucajung** [comment]
@timja I figured out where the issue is located and fixed it. Can I create a new branch or do I need any permissions?

**Comment by timja** [comment]
you will need to fork the repository and send a pull request from there, see https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by lucajung** [comment]
Thanks, you can delete your comments. They do not help some other users

**Comment by lucajung** [comment]
@timja Sorry to be impatient, but when can I expect my PR to be merged? :)

**Comment by timja** [comment]
Given there's no test coverage (which is a problem throughout this plugin).
I will need to manually test it.

I'll see if I can get to it today.

In the meantime you should be able to use this pre-release build:
https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/windows-azure-storage/380.vff140f4e18c8/windows-azure-storage-380.vff140f4e18c8.hpi

**Comment by lucajung** [comment]
Thank you very much!
