### ISSUE TITLE
Drop dependency on `blueocean-rest`

### ISSUE THREAD

**Issue by basil** [jenkinsci/azure-storage-plugin#278]
BlueOcean is deprecated and it is not desirable for this plugin to depend on it. It is not clear to me what value is provided by `AzureStorageBlueArtifact` but it would be nice if it could be deleted, along with the dependency on `blueocean-rest`.

**Comment by timja** [comment]
I believe it's needed to make artifact display work in blueocean for some reason. 

Can't remember the details on the bug though.
